/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlataformasRouteImport } from './routes/plataformas'
import { Route as AmigosAmigoIdRouteImport } from './routes/amigos.$amigoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformasRoute = PlataformasRouteImport.update({
  id: '/plataformas',
  path: '/plataformas',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosAmigoIdRoute = AmigosAmigoIdRouteImport.update({
  id: '/amigos/$amigoId',
  path: '/amigos/$amigoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/perfil': typeof PerfilRoute
  '/plataformas': typeof PlataformasRoute
  '/amigos/$amigoId': typeof AmigosAmigoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/perfil': typeof PerfilRoute
  '/plataformas': typeof PlataformasRoute
  '/amigos/$amigoId': typeof AmigosAmigoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/perfil': typeof PerfilRoute
  '/plataformas': typeof PlataformasRoute
  '/amigos/$amigoId': typeof AmigosAmigoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conquistas'
    | '/historico'
    | '/login'
    | '/metas'
    | '/perfil'
    | '/plataformas'
    | '/amigos/$amigoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conquistas'
    | '/historico'
    | '/login'
    | '/metas'
    | '/perfil'
    | '/plataformas'
    | '/amigos/$amigoId'
  id:
    | '__root__'
    | '/'
    | '/conquistas'
    | '/historico'
    | '/login'
    | '/metas'
    | '/perfil'
    | '/plataformas'
    | '/amigos/$amigoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConquistasRoute: typeof ConquistasRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  PerfilRoute: typeof PerfilRoute
  PlataformasRoute: typeof PlataformasRoute
  AmigosAmigoIdRoute: typeof AmigosAmigoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataformas': {
      id: '/plataformas'
      path: '/plataformas'
      fullPath: '/plataformas'
      preLoaderRoute: typeof PlataformasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos/$amigoId': {
      id: '/amigos/$amigoId'
      path: '/amigos/$amigoId'
      fullPath: '/amigos/$amigoId'
      preLoaderRoute: typeof AmigosAmigoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConquistasRoute: ConquistasRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  PerfilRoute: PerfilRoute,
  PlataformasRoute: PlataformasRoute,
  AmigosAmigoIdRoute: AmigosAmigoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
